apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "my-web-app.name" . }}
data:
  APP_ENV: {{ .Values.config.appEnv | quote }}
  APP_REGION: {{ .Values.config.appRegion | quote }}
  LOG_LEVEL: {{ .Values.config.logLevel | quote }}
  FEATURE_X_ENABLED: {{ .Values.config.featureXEnabled | quote }}