{{- if .Values.externalSecret.enabled }}

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret

metadata:
  name: {{ include "my-web-app.name" . }}-database

spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}

  secretStoreRef:
    name: {{ .Values.externalSecret.secretStore.name }}
    kind: {{ .Values.externalSecret.secretStore.kind }}

  target:
    name: {{ include "my-web-app.name" . }}-database
    creationPolicy: Owner

  data:
    - secretKey: DB_USERNAME
      remoteRef:
        key: {{ .Values.externalSecret.remoteSecret.key }}
        property: username

    - secretKey: DB_PASSWORD
      remoteRef:
        key: {{ .Values.externalSecret.remoteSecret.key }}
        property: password

{{- end }}