apiVersion: v1
kind: Pod
metadata:
  name: storage-test
  namespace: helm-learning
spec:
  containers:
    - name: test
      image: busybox:1.36
      command:
        - sh
        - -c
        - |
          echo "Container started"
          sleep 3600