apiVersion: v1
kind: Pod
metadata:
  name: graceful-test
  namespace: helm-learning

spec:
  terminationGracePeriodSeconds: 20

  containers:
    - name: graceful-test
      image: busybox:1.36

      command:
        - /bin/sh
        - -c
        - |
          trap 'echo "SIGTERM RECEIVED"; echo "Application cleanup..."; sleep 5; echo "Application cleanup complete"; exit 0' TERM

          echo "Application started"

          while true; do
            sleep 1
          done

      lifecycle:
        preStop:
          exec:
            command:
              - /bin/sh
              - -c
              - |
                echo "preStop started"
                sleep 5
                echo "preStop complete"