apiVersion: v1
kind: Pod
metadata:
  name: s3-pod
  namespace: va-test
spec:
  serviceAccountName: s3-sa
  containers:
    - name: aws-cli
      image: public.ecr.aws/aws-cli/aws-cli:latest
      command: ["sleep", "3600"]